### ISSUE TITLE
Assertion `mutex->__data.__owner == 0' failed.

### ISSUE THREAD

**Issue by carojasq** [bioinfomaticsCSU/EPGA2#2]
Hi, 
I was running EPGA2 but i got this error:

```
09-19 / 07:27:17        -------------------Total time Wallclock  1307.66 s
09-19 / 07:28:44        sh: 1: pause: not found
09-19 / 10:38:11        EPGA: ../nptl/pthread_mutex_lock.c:80: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
```

My time.txt file:

```
bless start--:Sat Sep 19 01:24:42 2015
DSK start--:Sat Sep 19 06:35:17 2015
GetKmerHash start--:Sat Sep 19 06:57:57 2015
DSK k+1-mer start--:Sat Sep 19 07:05:29 2015
bcalm start--:Sat Sep 19 07:28:45 2015
SimplePathToGraph start--:Sat Sep 19 08:27:29 2015
EPGA start--:Sat Sep 19 08:30:12 2015
105139514
library_0.1.corrected.fastq library_0.2.corrected.fastq 180 7 0
end--:Sat Sep 19 10:38:12 2015

```

As a suggestion i think would be better to put all the source code available in this repo due to library dependencies in the available binaries. 

Thanks a lot for your help!

**Comment by bioinfomaticsCSU** [comment]
Hi,
Thank you very much! I will update the program as soon as possible! I will notify you when i finish the update. Thanks again!

**Comment by carojasq** [comment]
Hi,

Any news about this issue?
Thanks

**Comment by bioinfomaticsCSU** [comment]
Hi
Now, we have fixed some bugs, you could download and run it as before(note that bcalm should be created in folder Bcalm2). If you have any problem, please let me know, thanks very much.
We will upload a new version of EPGA2 with "makefile" to resolve problems of compling, The new version will upload about ten days later.

**Comment by carojasq** [comment]
Hi, 

Any new about this issue? 

Thanks.

**Comment by bioinfomaticsCSU** [comment]
Hi
I am sorry and apologize for our delay about the new version. It wil be published in this week. Thanks.
By the way, can EPGA2 about current version run correctly and get the final results? Thanks very much.

**Comment by carojasq** [comment]
I've pulled the full repository, compiled bcalm, copied bcalm to the right folder but I'm still having the same  issue:

10-16 / 09:56:14        EPGA: ../nptl/pthread_mutex_lock.c:80: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.

Mi time.txt file

```
bless start--:Thu Oct 15 23:03:30 2015
DSK start--:Fri Oct 16 04:21:42 2015
GetKmerHash start--:Fri Oct 16 05:23:00 2015
DSK k+1-mer start--:Fri Oct 16 05:30:42 2015
bcalm start--:Fri Oct 16 06:33:02 2015
SimplePathToGraph start--:Fri Oct 16 07:39:54 2015
EPGA start--:Fri Oct 16 07:44:44 2015
105139514
library_0.1.corrected.fastq library_0.2.corrected.fastq 180 7 0
end--:Fri Oct 16 09:56:16 2015
```

**Comment by bioinfomaticsCSU** [comment]
Hi
Please see "https://github.com/bioinfomaticsCSU/EPGA2.1", the new version. Download all file, and type "make all". Please see README.md. If you have any problem, please let me know, thanks very much.

**Comment by carojasq** [comment]
Hi, 
With the last update I was able to run successfully EPGA2.  Thanks a lot!!!
